name: taskgate_sdk
description: TaskGate SDK for Flutter - integrate with TaskGate to receive task requests and report completion.
version: 1.0.2
homepage: https://taskgate.co
repository: https://github.com/task-gate/taskgate-sdk-flutter

false_secrets:
  - /assets/**
  - /ios/vendor/**
  - /**/*.key
  - /**/keystore.txt
  - /**/firebase_app_id_file.json

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.taskgate.sdk.flutter
        pluginClass: TaskGateSdkPlugin
      ios:
        pluginClass: TaskGateSdkPlugin
